<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10030" started-at="2019-07-24T10:05:23Z" finished-at="2019-07-24T10:05:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10030" started-at="2019-07-24T10:05:23Z" finished-at="2019-07-24T10:05:33Z">
      <class name="API_CALLS.SCRIPTS.testCASE">
        <test-method status="PASS" signature="GetWeatherDetails(org.testng.ITestContext)[pri:0, instance:API_CALLS.SCRIPTS.testCASE@26be92ad]" name="GetWeatherDetails" duration-ms="4885" started-at="2019-07-24T10:05:23Z" finished-at="2019-07-24T10:05:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f9d02cb]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetWeatherDetails -->
        <test-method status="FAIL" signature="RegistrationSuccessful(org.testng.ITestContext)[pri:0, instance:API_CALLS.SCRIPTS.testCASE@26be92ad]" name="RegistrationSuccessful" duration-ms="5081" started-at="2019-07-24T10:05:28Z" finished-at="2019-07-24T10:05:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f9d02cb]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<27.46 Degree celsius> but was:<30.32 Degree celsius>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<27.46 Degree celsius> but was:<30.32 Degree celsius>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:71)
at API_CALLS.SCRIPTS.testCASE.RegistrationSuccessful(testCASE.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegistrationSuccessful -->
      </class> <!-- API_CALLS.SCRIPTS.testCASE -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
